package org.erp.sms.common.enums;

public enum ExpenseCategory {
    SALARIES_BENEFITS,
    UTILITIES,
    OFFICE_SUPPLIES,
    EQUIPMENT_FURNITURE,
    MAINTENANCE_REPAIRS,
    MARKETING_ADVERTISING,
    TRAVEL_TRANSPORTATION,
    PROFESSIONAL_SERVICES,
    MISCELLANEOUS
}
